# Site settings
title: HIPython
email: katyhuff@gmail.com
description: "Website for Hack Illinois Python"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arfc.github.io/hipython" # the base hostname & protocol for your site
twitter_username: katyhuff
github_username: arfc
logo: "/img/logo.svg"

# Agency color settings
color:
  primary: e87722
  primary-dark: d45d00
  secondary: 606eb2
  secondary-dark: 002058
  transparent: rgba(0,21,56,0.7)

# Build settings
markdown: kramdown
permalink: pretty
